### ISSUE TITLE
Should check the constructor function name

### ISSUE THREAD

**Issue by blakeembrey** [inspect-js/is-generator-function#1]
Using the regexp solution is buggy and inefficient. An easier check is to just `fn.constructor.name === 'GeneratorFunction'`.

**Comment by ORESoftware** [comment]
Would this https://github.com/ljharb/is-generator-function/issues/7 solve THIS?

**Comment by ljharb** [comment]
Nope, per my comment on the issue, `toString` output is not sufficient to reliably determine if something's a generator on every engine.

I agree that transpilers are far more relevant now than they were in May of 2014, but what babel provides is not a generator, and so those functions should return false here.
