### ISSUE TITLE
CSP warning in Firefox

### ISSUE THREAD

**Issue by feross** [inspect-js/is-generator-function#41]
"Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”)."

### Expected Behavior

No CSP warnings. Is there any other way to detect generator support?

### To Reproduce

When this code is run by next.js in Firefox, the warnings appears:

```js
	try {
		return Function('return function*() {}')();
	} catch (e) {
	}
```

Related issue: https://github.com/vercel/next.js/issues/23587

**Comment by ljharb** [comment]
No, there is no other way to detect support for syntax. Enabling CSP means your app simply can't use anything that depends on that detection.

**Comment by ljharb** [comment]
One thing you can do if you know you're targeting only browsers where the value is `true` is configure your bundler to replace  the internal `getGeneratorFunc` function with `() => function*() {}`, but that's not an option if you support browsers where it might be `false`.

**Comment by feross** [comment]
@ljharb Thanks for the tip about configuring the bundler - we may look into that.

One thing I think we can still do here to improve things is to lazily run the `Function()` constructor only when it is needed. Right now it's being run at the top level, even if `isGeneratorFunction` is never actually called.

Furthermore, even if `isGeneratorFunction` *is* called, we may not need to to run `Function()` if the earlier `isFnRegex` test passes:

```js
	if (isFnRegex.test(fnToStr.call(fn))) {
		return true;
	}
```

So I think this means we can make the CSP error go away in most cases.

**Comment by ljharb** [comment]
That's a fair point - I'll make that change.
