### ISSUE TITLE
Did you delete the version ？（ is-generator-function@1.0.9）

### ISSUE THREAD

**Issue by lzt853884319** [inspect-js/is-generator-function#42]
When i excute npm install is-generator-function@1.0.9 ；
I get this error:    No matching version found for is-generator-function@1.0.9;
But this version is always shown on https://web-bnpm.byted.org/package/is-generator-function；

And excute npm view is-generator-function  versions. I get [
  '1.0.0', '1.0.1',
  '1.0.2', '1.0.3',
  '1.0.4', '1.0.5',
  '1.0.6', '1.0.7',
  '1.0.8'
]

**Comment by ljharb** [comment]
I have no idea what that website is - npm is https://www.npmjs.com/package/is-generator-function
