### ISSUE TITLE
Put Function.prototype.toString test last?

### ISSUE THREAD

**Issue by otakustay** [inspect-js/is-generator-function#9]
I tried to compare the performance of 3 ways checking generator function, [here is the jsperf.com page](https://jsperf.com/generator-function-check/1)

It seems the performance is `Obejct#toString` > `Object.getPrototypeOf` > `Function#toString`, so it is better to place `Object#toString` and `Object.getPrototypeOf` before the `Function#toString` check, it seems no compatibility issue to me.

If acceptable, I can create a pull request for this issue.

**Comment by ljharb** [comment]
Determining if a function is a generator function or not isn't something that should happen in performance-critical code, so it's not hugely important.

That said, the ordering actually might matter here - we'd need to verify if there are any engines that lack `Symbol.toStringTag`, have native generator functions, and have toString output that is not `[object GeneratorFunction]` - if there are none, then probably the Object#toString check could be hoisted above the fnToStr check.

**Comment by otakustay** [comment]
> Determining if a function is a generator function or not isn't something that should happen in performance-critical code, so it's not hugely important.

In my case I'm developing a redux middleware which consumes generator functions, so it is required to check function type frequently, performance is a consideration

I'm wondering why `toStringTag` must be checked before `Obejct#toString` can be used, isn't `Object.prototype.toString.call(any) ==='[object GeneratorFunction]'` always reliable?

**Comment by ljharb** [comment]
@otakustay why does your middleware require a generator, as opposed to a function that returns an iterator? For example, `function () { return [1, 2, 3].keys(); }` works in place of a generator perfectly well, but would fail your check.

As I recall, there are some engines where the toString value is `[object Function]`, which is why I made it a definite-positive, but not a definite-negative.

**Comment by otakustay** [comment]
> why does your middleware require a generator, as opposed to a function that returns an iterator?

Because many projects is using redux-thunk already, to be compatible with it my middleware should consume only generator functions, leave plain functions to redux-thunk, or else I would be required to embed redux-thunk implement in my lib

> As I recall, there are some engines where the toString value is [object Function], which is why I made it a definite-positive, but not a definite-negative.

I think `Object#toString` is not a break path, if this returns `[object Function]`, `Function#toString` will be a fallback check which give the correct result

It may lead to extra cost if engine does not support `[object GeneratorFunction]` at all, but since `Object#toString` is super fast (compares to `Function#toString` which depends on the code length of function), it seems better to put it before others

Or is it possible to have `isGeneratorFunction` implement on whether `toStringTag` is supported, put `Object#toString` and `Object.getPrototypeOf` in earlier paths if `toStringTag` is supported, other wise return the current implement

**Comment by ljharb** [comment]
I'm fine with branching and having different orderings based on whether the env supports Symbol.toStringTag.

If you'd like to make a PR, that'd be great; but it'll need very extensive testing, in every version of every browser and node as far back as native generators and/or Symbol.toStringTag are supported in that engine.

**Comment by otakustay** [comment]
OK，I'll make this pull request and test it all browser that supports generators:

- Edge >= 13
- Firefox >= 26
- Chrome >= 39
- Safari >= 10
- Opera >= 26
- Node >= 6.4.0 (test only minor version, not all patch versions)

This may take a long time but I will own it

**Comment by ljharb** [comment]
@otakustay node supports generators down to 0.11 with `--harmony`; please test down to there as well.

**Comment by otakustay** [comment]
@ljharb OK, node testing is much more easier :)

**Comment by otakustay** [comment]
@ljharb I will, most likely in two weeks since I'm really busy recently, I would put this on my todo list

**Comment by otakustay** [comment]
When testing [this commit](https://github.com/otakustay/is-generator-function/commit/934ad50e9883f5c75fc0c526800fca9a5c3181a9) on travis it seems some test cases are failing when branch order changes, it could be unsafe for this change, I'd like to keep the current order and close this issue, sorry for it :)

**Comment by otakustay** [comment]
[Node v4](https://travis-ci.org/otakustay/is-generator-function/jobs/386996605) and [Node v8](https://travis-ci.org/otakustay/is-generator-function/jobs/386996606) tests seems to be failed, I think at least v8 should not fail

**Comment by ljharb** [comment]
That’s just the code coverage, not the tests, and those are allowed to fail. I’m going to reopen this; a PR (and further manual testing) would be appreciated.

**Comment by otakustay** [comment]
OK, I'm currently searching for a solution to test in multiple old browsers, testling seems out of service and browserstack is really too expensive for me :)

**Comment by ljharb** [comment]
Browserstack has 2 hours free a month, i believe, on their free account.

**Comment by ljharb** [comment]
I tweaked the change and tested in IE 6-11, Edge 15-18, Chrome 15, Firefox 3/3.6/4-6, Safari 4/5/5.1/6/7.1. I think this can land.

**Comment by ljharb** [comment]
Unfortunately, I had to revert this in 3892c18 - turns out node 0.12 - 5 all fail with the order reversed.
